AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  openbanking-expenses-ingest

  Exports expenses to google sheets using OpenBanking via the GoCardless Bank Account Data API

Parameters:
  BankName:
    Type: String
    Description: The name of the bank institution to use to authenticate with
    Default: Starling Bank
  BankCountry:
    Type: String
    Description: The country of the bank instutution to use
    Default: GB
  RequisitionNotificationAddress:
    Type: String
    Description: The email address to notify when user action is needed to generate a requisition

Resources:
  UpdateApiCredentialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Renews or refreshes the access token for the GoCardless Bank Account Data API where necessary
      CodeUri: functions/update-api-credentials/
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Handler: index.handler
      Timeout: 30
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'GoCardless/*'
        - KMSDecryptPolicy:
            KeyId: !Ref KmsKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        EntryPoints:
          - index.ts
  
  UpdateRequisitionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Renews or refreshes the requisition for the GoCardless Bank Account Data API where necessary
      CodeUri: functions/update-requisition/
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Handler: index.handler
      Timeout: 30
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RequisitionTable
        - DynamoDBWritePolicy:
            TableName: !Ref RequisitionTable
        - KMSDecryptPolicy:
            KeyId: !Ref KmsKey
        - KMSEncryptPolicy:
            KeyId: !Ref KmsKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        EntryPoints:
          - index.ts
  
  IngestSharedExpensesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/openbanking-expenses-ingest.json
      DefinitionSubstitutions:
        UpdateApiCredentialsFunctionARN: !Ref UpdateApiCredentialsFunction
        UpdateRequisitionFunctionARN: !Ref UpdateRequisitionFunction
        SsmKeyId: !Ref KmsKey
        SecretIdParamName: /GoCardless/Secret-Id
        SecretKeyParamName: /GoCardless/Secret-Key
        AccessTokenParamName: /GoCardless/Access-Token
        AccessTokenExpiresParamName: /GoCardless/Access-Token-Expires
        RefreshTokenParamName: /GoCardless/Refresh-Token
        RefreshTokenExpiresParamName: /GoCardless/Refresh-Token-Expires
        RequisitionReferenceParamName: /GoCardless/Requisition-Reference
        BankName: !Ref BankName
        BankCountry: !Ref BankCountry
        RequisitionTableName: !Ref RequisitionTable
        RequisitionNotificationTopic: !Ref RequisitionSnsTopic
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateApiCredentialsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateRequisitionFunction
        - SSMParameterReadPolicy:
            ParameterName: 'GoCardless/*'
        - KMSDecryptPolicy:
            KeyId: !Ref KmsKey
        - KMSEncryptPolicy:
            KeyId: !Ref KmsKey
        - SNSPublishMessagePolicy:
            TopicName: GoCardless-Bank-Account-Data-Agreement
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/GoCardless/*'
            - Effect: Allow
              Action:
                - kms:GenerateDataKey
              Resource: !GetAtt KmsKey.Arn

  RequisitionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GocCardless-Requisition
      AttributeDefinitions:
        - AttributeName: reference
          AttributeType: S
      KeySchema:
        - AttributeName: reference
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        KMSMasterKeyId: !Ref KmsKey
        SSEEnabled: true
        SSEType: KMS
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
  
  RequisitionSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: GoCardless-Bank-Account-Data-Agreement
      DisplayName: GoCardless Bank Account API agreement notification
      KmsMasterKeyId: !Ref KmsKey
      Subscription:
        - Endpoint: !Ref RequisitionNotificationAddress
          Protocol: email

  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: The key used to encrypt sensitive information related to the openbanking-expenses-ingest service
      KeyPolicy:
        Version: '2012-10-17'
        Id: openbanking-expenses-ingest-key-policy
        Statement:
          - Sid: Enable Root User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  
  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/Openbanking-Expenses-Ingest
      TargetKeyId: !Ref KmsKey
